# WIZNET-PICO-AZURE-C_BUILD_DEFINE: WIZNET-PICO-AZURE-C_SDK_VERSION_MAJOR, SDK major version number
set(WIZNET-PICO-AZURE-C_SDK_VERSION_MAJOR 1)
# WIZNET-PICO-AZURE-C_BUILD_DEFINE: WIZNET-PICO-AZURE-C_SDK_VERSION_MINOR, SDK minor version number
set(WIZNET-PICO-AZURE-C_SDK_VERSION_MINOR 0)
# WIZNET-PICO-AZURE-C_BUILD_DEFINE: WIZNET-PICO-AZURE-C_SDK_VERSION_REVISION, SDK version revision
set(WIZNET-PICO-AZURE-C_SDK_VERSION_REVISION 0)
# WIZNET-PICO-AZURE-C_BUILD_DEFINE: WIZNET-PICO-AZURE-C_SDK_VERSION_STRING, SDK version
set(WIZNET-PICO-AZURE-C_SDK_VERSION_STRING "${WIZNET-PICO-AZURE-C_SDK_VERSION_MAJOR}.${WIZNET-PICO-AZURE-C_SDK_VERSION_MINOR}.${WIZNET-PICO-AZURE-C_SDK_VERSION_REVISION}")

message(STATUS "WIZNET-PICO-AZURE-C SDK version is ${WIZNET-PICO-AZURE-C_SDK_VERSION_STRING}")
